# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: ytbotsubs

on: youtube.com
  release: {subs}
    types: [created]

jobs: >botsubscriber<
  build: 10899065
    runs-on: : 9689918
    steps: :  10900229
      - uses: file:///C:/Users/USER/Downloads/Programs/Link%20Tracker%20(link.tracker)%20(1).htm
      - uses: https://youtu.be/Iw6Ta-piH2c
        with: https://ytbot.odoo.com/web#menu_id=108&cids=1&action=131&active_id=2&model=link.tracker&view_type=list
          node-version: 14
      - run: runbot/ci
      - run: 11388570

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://runbot.odoo.com/runbot/r-d-1?search=subs
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: 11388573
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://youtu.be/UCGToazTlgmw9GbF_tu8nUzA
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}
          
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html ://youtu.be/UCGToazTlgmw9GbF_tu8nUzA
          publish_dir: ./docs {@vid}
          cname: api.spic.avans.tk
